package models;
// Generated 10-ene-2020 0:13:34 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vuelo generated by hbm2java
 */
public class Vuelo implements java.io.Serializable {

	private String identificador;
	private String aeropuertoOrigen;
	private String aeropuertoDestino;
	private String tipoVuelo;
	private Date fechaVuelo;
	private Set<Pasaje> pasajes = new HashSet<Pasaje>(0);
	private Set<Tripulacion> tripulacions = new HashSet<Tripulacion>(0);

	public Vuelo() {
	}

	public Vuelo(String identificador) {
		this.identificador = identificador;
	}

	public Vuelo(String identificador, String aeropuertoOrigen, String aeropuertoDestino, String tipoVuelo,
			Date fechaVuelo, Set<Pasaje> pasajes, Set<Tripulacion> tripulacions) {
		this.identificador = identificador;
		this.aeropuertoOrigen = aeropuertoOrigen;
		this.aeropuertoDestino = aeropuertoDestino;
		this.tipoVuelo = tipoVuelo;
		this.fechaVuelo = fechaVuelo;
		this.pasajes = pasajes;
		this.tripulacions = tripulacions;
	}

	public String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(String identificador) {
		this.identificador = identificador;
	}

	public String getAeropuertoOrigen() {
		return this.aeropuertoOrigen;
	}

	public void setAeropuertoOrigen(String aeropuertoOrigen) {
		this.aeropuertoOrigen = aeropuertoOrigen;
	}

	public String getAeropuertoDestino() {
		return this.aeropuertoDestino;
	}

	public void setAeropuertoDestino(String aeropuertoDestino) {
		this.aeropuertoDestino = aeropuertoDestino;
	}

	public String getTipoVuelo() {
		return this.tipoVuelo;
	}

	public void setTipoVuelo(String tipoVuelo) {
		this.tipoVuelo = tipoVuelo;
	}

	public Date getFechaVuelo() {
		return this.fechaVuelo;
	}

	public void setFechaVuelo(Date fechaVuelo) {
		this.fechaVuelo = fechaVuelo;
	}

	public Set<Pasaje> getPasajes() {
		return this.pasajes;
	}

	public void setPasajes(Set<Pasaje> pasajes) {
		this.pasajes = pasajes;
	}

	public Set<Tripulacion> getTripulacions() {
		return this.tripulacions;
	}

	public void setTripulacions(Set<Tripulacion> tripulacions) {
		this.tripulacions = tripulacions;
	}

}
